<?php
/**
 * Created by PhpStorm.
 * User: symphp
 * Date: 2017/5/21
 * Time: 13:42
 */
class Mymodel extends Medoo\Medoo
{
    /**
     * 表名
     * @var
     */
    public $_table;
    /**
     * 初始化Medoo
     * Mymodel constructor.
     */
    public function __construct()
    {
        parent::__construct(conf::get('database'));
    }

    /**
     * 查询数据
     * @param null $columns
     * @param null $where
     * @param null $join
     * @return array|bool
     */
    public function _select($columns = null, $where = null,$join = null)
    {
        if($join === null) {
            return parent::select($this->_table, $columns, $where);  // TODO: Change the autogenerated stub
        } else {
            return parent::select($this->_table, $join, $columns = null, $where = null);
        }
    }

	/**
	 * @param $datas array 支持二维数组
	 * @return int|string 成功id
	 */
    public function _insert($datas)
    {
        parent::insert($this->_table, $datas); // TODO: Change the autogenerated stub
		return parent::id();
    }

	/**
	 * 更新数据
	 * @param $data array 修改数据
	 * @param null $where
	 * @return int count 影响行数
	 */
    public function _update($data, $where = null)
	{
		return parent::update($this->_table, $data, $where)->rowCount(); // TODO: Change the autogenerated stub
	}

	/**
	 * 删除数据
	 * @param $where
	 * @return int 影响行数
	 */
	public function _delete($where)
	{
		return parent::delete($this->_table, $where)->rowCount(); // TODO: Change the autogenerated stub
	}


}